site_name: Speedrunners Wiki
site_url: https://starfilledsky.github.io/SR-Wiki/
repo_url: https://github.com/StarFilledSky/SR-Wiki/
docs_dir: src/
site_dir: docs/



markdown_extensions:
  - admonition
  - attr_list 
  - toc:
      permalink: "✿"
  # I don't think I need these for now
  # - pymdownx.details
  # - pymdownx.superfences

plugins:
  - search
  - autorefs
  - document-dates:
      position: bottom 

  # - autorefs #todo look into

extra_css:
  - assets/stylesheets/extra.css


theme:
  favicon: assets/images/favicon.ico
  name: material
  language: en
  
  features:
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow
    # - toc:
    #   permalink: true
    # - toc(permalink=true): #haven't gotten this working yet
    #   permalink: "✿"

  palette:
    - scheme: slate
      toggle:
          icon: material/brightness-4
          name: Switch to light mode
      primary: deep purple
      accent: blue

    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

